name: Ywam Cusco
favicon: null
layout_spectrum: 0.51354
typography_spectrum: 0.7352445
title: Youth With A Mission Cusco
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a4a4a4'
    - '#fbffff'
    - '#191410'
    - '#b4622c'
    - '#ffe1a2'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
